database_path: "database/"
gisdata_path: "gisdata/"
grid_file: "grid.csv"
wind_grid_file: "wind_grid.xlsx"
kepco_file: "KEPCO.xlsx"
carbonprice_file: "NGFS_carbonprice.xlsx"
cluster_file: "clusterpolygon.gpkg"
db_semippa_file: "db_semippa.gpkg"
grid_buffer_file: "grids_within_modified_buffer.gpkg"
load_patterns_db: "load_patterns.db"
solar_patterns_db: "solar_patterns.db"
wind_patterns_db: "wind_patterns.db"